### ISSUE TITLE
Make the bundle Symfony 3.0 compliant

### ISSUE THREAD

**Issue by tbyte80** [lennerd/VipxBotDetectBundle#10]
... by changing **line 92** in BotDetector.php from

`return $this->metadatas = require $cache;`

to

`return $this->metadatas = require $cache->getPath();`

**Comment by lennerd** [comment]
Are you able to make a PR for this and add the new version to the composer file? This way we can run all the tests and see if your changes are enough to make the new Symfony version work.

**Comment by lennerd** [comment]
Ping @tbyte80

**Comment by samdjstevens** [comment]
I'd be happy to make a PR for this to get Symfony 3.0 compatibility, but I can't see any reference to line mentioned above in the bundle anywhere?

**Comment by samdjstevens** [comment]
Ah, I needed to look at the underlying package the bundle uses. It looks like the Symfony 3.0 updates have been made in the bundle - would this mean its just a case of updating the composer.json?

**Comment by lennerd** [comment]
This is fixed in the underlaying library (see https://github.com/lennerd/vipx-bot-detect/issues/37).

Never the less I would be happy to get your PR to fix this. What needs to be done is fixing the composer file and automatic tests running via Travis to test against Symfony 3. A good reference for this is again the base library.

https://github.com/lennerd/vipx-bot-detect/blob/master/composer.json#L17-L18
https://github.com/lennerd/vipx-bot-detect/blob/master/.travis.yml#L20-L27

**Comment by samdjstevens** [comment]
Hey, 

I've made the PR (#14) - hope that everything is in order in it, if not let me know what I need to change!

Cheers

**Comment by lennerd** [comment]
Closed with #14.
